### ISSUE TITLE
[BUG] Uncaught (in promise) ReferenceError: process is not defined

### ISSUE THREAD

**Issue by victor-heliomar** [lennartdeknikker/storybook-addon-jira#4]
## Explanation

I tried to install and use the addon but the issue is loading eternally. When I click on the `reload` button I get the next error:

![image](https://user-images.githubusercontent.com/66505715/210370797-b07b0bce-27d1-45b7-b398-7a6f329e89fe.png)

I checked the path `/api` and it works properly, it's getting the info of the issues if I use it with a `?ticketId` query param

![image](https://user-images.githubusercontent.com/66505715/210371533-795301ae-e620-479d-899d-f99a5e7373f5.png)

But the storybook is never receiving the issue properly

![image](https://user-images.githubusercontent.com/66505715/210371670-50eab41d-64cb-43c6-b9ce-640b2251d227.png)

## Technical details

Framework: Next.js 13.0.7
NodeJS version: 18.12.1
Webpack Version used for storybook: builder-webpack5

<details>
    <summary>Main configuration</summary>
<pre>
    module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    "storybook-addon-sass-postcss",
    "@storybook/addon-a11y",
    "storybook-jira-addon"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5"
  }
}
</pre>
</details>

<details>
    <summary>Middleware file</summary>
<pre>
const fetch = require("node-fetch");
module.exports = function expressMiddleware (router) {
  router.get('/api', (req, res) => {
      const myHeaders = new fetch.Headers();
      const authHeader = `Basic ${Buffer.from(`${process.env?.STORYBOOK_JIRA_USERNAME}:${process.env?.STORYBOOK_JIRA_API_KEY}`).toString('base64')}`
      myHeaders.append("Authorization", authHeader);

      const requestOptions = {
        method: 'GET',
        headers: myHeaders,
        redirect: 'follow'
      };

      fetch(`${process.env.STORYBOOK_JIRA_API_ENDPOINT}/${req.query?.ticketId}`, requestOptions)
        .then(response => response.json())
        .then(result => {
          res.send(result)
        })
        .catch(error => console.log('error', error));
  })
}
</pre>
</details>

**Comment by mafernandezgo** [comment]
Hello Victor, have you found a way to solve it? I'm having the same error

**Comment by victor-heliomar** [comment]
Hi @mafernandezgo, I haven't found any solution to this problem. I think it's a problem related to the NextJs framework and how it is handling the environment variables. I think we should find a way to access to the process object in the client side to solve this problem

**Comment by victor-heliomar** [comment]
Maybe adding that object globally in the preview.js file it could work, I'm not sure, I'll try later

**Comment by victor-heliomar** [comment]
> Hello Victor, have you found a way to solve it? I'm having the same error

I added a `window.process = {}` in the preview.js file and it works relatively fine, at least it already shows me the tasks when I refresh it

![image](https://user-images.githubusercontent.com/66505715/211859204-7f9acbad-1665-41ba-a5a4-cc9ba165ecba.png)

Without that definition in the `preview.js` file the app crash when I click in refresh button

![image](https://user-images.githubusercontent.com/66505715/211859346-7251d141-8550-40e2-b780-417497d12f7a.png)

**Comment by victor-heliomar** [comment]
Checking in the code, it doesn't require to access to `process.env.STORYBOOK_MIDDLEWARE_JIRA_ENDPOINT`, it's just using it to check if you want to use a custom STORYBOOK_MIDDLEWARE_JIRA_ENDPOINT, but if you don't define that variable then it uses the `localhost:6006/api` endpoint to access to it

![image](https://user-images.githubusercontent.com/66505715/211859580-6d573b1d-bdde-45be-b2ef-68f949788f3b.png)

So I think to fix this error we should handle the error and prevent the app from crash if process is not defined, since it's not 100% required
